services:
  rails_app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: rails_app
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_NAME: postgres
      POSTGRES_HOST: db
      POSTGRES_DB: ${POSTGRES_DB}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      RAILS_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - db


    volumes:
      - ./:/backend

  db:
    image: postgres:14
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: rails_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
